### PR TITLE
Missing fr_FR translation files

### PR DESCRIPTION
**Pull request by athiry**
Added languages woocommerce-myparcel-fr_FR.po

### CODE REVIEW

**Comment by athiry** [comment]
See https://github.com/myparcelnl/woocommerce/issues/590 and https://github.com/myparcelbe/woocommerce/issues/154 for reasons of this fix

**Comment by RichardPerdaan** [comment]
Hi @athiry ,

This problem should already be solved in version 4.3.0 of the MyParcel WooCommerce plugin.

Would you like to try this version?
For proper operation, please uninstall the current version of the plugin and install v4.3.0 by uploading the .zip file.
You can find the .zip here: https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.0

**Comment by RichardPerdaan** [comment]
Hi @athiry ,
The fr_FR translation is included in version 4.3.2 of the MyParcel plugin.

**Comment by athiry** [comment]
Ok, could you push this fix to myparcelbe as well ? Thanks.
See https://github.com/myparcelbe/woocommerce/issues/154

**Comment by RichardPerdaan** [comment]
Hi @athiry ,
We are going to align the code from WooCommerce NL to WooCommerce BE. This issue will automatically be included. 

Because many parts have been improved in the NL version, it may take a while before we have transferred everything. But we will certainly start with this.

**Pull request closed without merging**
