### PR TITLE
Changed translation afgevinkt/uitgevinkt by settings checkout/fields ..

### PR DESCRIPTION
**Pull request by nickurt**
The using of "[aanvinken](https://www.encyclo.nl/begrip/aanvinken)" and "[afvinken](https://www.encyclo.nl/begrip/afvinken)" means both you need to "mark (check)" this option, but for the use of the WooCommerce address-fields you need to "unmark (uncheck)" this option, its better to use the "[uitvinken](https://www.encyclo.nl/begrip/uitvinken)"-verb

### CODE REVIEW

**Comment by EdieLemoine** [comment]
You're correct. We had a discussion about this but it was literally lost in translation as apparently the wrong verb is still in there. 👍

**Comment by nickurt** [comment]
It seems this is still not fixed ..

**Comment by EdieLemoine** [comment]
> It seems this is still not fixed ..

We need to add this manually, we can't just merge your PR.  

@RichardPerdaan?

**Comment by RichardPerdaan** [comment]
It will be included in the next version

**Comment by nickurt** [comment]
Thank you! :tada:

**Pull request closed without merging**
